#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	TFileHandle Handle; // will keep track of our file
	TFileIOResult Result; // will store our IO results
	string Name = "test.txt"; // the name of our file
	int Size = 100; // will store our file size
	byte CR = 0x0D; // define CR (carriage return)                        ""
	byte LF = 0x0A; // define LF (line feed)               "changed for ANSI compatibility"

	string sMessage; // we will write this to the file

	Delete("test.txt", Result);
	OpenWrite(Handle, Result, Name, Size); // open the file for writing (creates the file if it does not exist)

	nMotorEncoder[motorA] = 0;
	ClearTimer(T1);
	while (time1[T1] < 5000)
	{
		sMessage = nMotorEncoder[motorA];
		WriteText(Handle, Result, sMessage); // write 'sMessageToWrite' to the file
		WriteByte(Handle, Result, CR); // write 'CR' to the file (carriage return)
		WriteByte(Handle, Result, LF); // write 'LF' to the file (line feed)
		wait1Msec(250);
	}

	Close(Handle, Result); // close the file (DON'T FORGET THIS STEP!)
}
